
---
- hosts: webserver
  become: True
  tasks: 
   - name: Docker Starting
     docker_container:
       name: docker
       command: systemctl restart docker
       
   - name: Creating docker image
     docker_container:
       name: myapp
       image: php:8.0.9-apache
       state: started
       recreate: yes
       exposed_ports:
         - 80
       volumes_from:
         - . /var/www/html
      


...
